version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.12
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose version
      - run:
          name: Build Docker Image
          command: docker build -t my-python-dev-container .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
