name: Build, Test, and Push DevContainer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t my-tealscript-dev-container .

      - name: Run container and test installation
        run: |
          docker run --privileged --rm my-tealscript-dev-container bash -c "
            docker --version &&
            docker compose version &&
            git --version &&
            npm --version &&
            python3.12 --version &&
            algokit --version &&
            algokit localnet start
          "

      - name: Tag the Docker image
        run: docker tag my-tealscript-dev-container danieltambee/my-tealscript-dev-container:latest

      - name: Push the Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-tealscript-dev-container:latest
